server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'users'

queue:
  user: user
  password: pass1
  hostname: logs_rabbitmq
  port: 5672

jwt:
  expiresIn: 3600

service:
  id: 0
  name: USERS